### ISSUE TITLE
Add an ability to edit your order after finalizing

### ISSUE THREAD

**Issue by alexander-serebriyan** [vladislav-kovchug/food-order#1]
When you click "Finish my order" it is impossible to edit positions even though group order is still in progress. I would like to "unfreeze" my order and make edits if the group order is not finished.

**Comment by vladislav-kovchug** [comment]
Implemented in the 027555a5a0066fbfbc704e7bafa26426463f80a1

**Comment by vladislav-kovchug** [comment]
test comment

**Comment by vladislav-kovchug** [comment]
close the issue
